all:
    # hosts:
    vars:
        common_var1: true
    children:
        my-servers:
            vars:
                myserver_v1: true
            children:
                    servers-g1:
                        hosts:
                            ec2-52-91-27-196.compute-1.amazonaws.com
                        vars:
                            v1: true
                            ansible_ssh_private_key_file: /root/.ssh/aws-ec21.pem
                    servers-g2:
                        hosts:
                            52.91.27.196
                        vars:
                            v2: true
        db-servers:
            hosts:
                52.91.27.196
            vars:
                db_name: mongodb
        ungrouped:
            # vars:
            # hosts:
                # localhost